base weapon recoil generation change+ small bugfix
LiddulBOFH/ACF-3-SWEPs pull request #3
Opened 2024-09-27 22:32 UTC by LeninCat

-Removed intense screenshake from aimpunch produced by high latency
-Added client initiated muzzle climb recoil
-Fixed recoil and aimpunch being applied while sprinting

2024-09-30 13:44 UTC, LiddulBOFH requested changes
May want to still keep Ply as a localized version of the player, calling self.Owner repeatedly is not good for performance due to the extremely inefficient metatable index entities have, and self:GetOwner() is preferred over self.Owner
"IFTP" is also not needed as it is only being used once, not to mention its being defined in the global space when it should be localized
"ang" should also be localized

2024-09-30 17:33 UTC, LeninCat commented
changes has been applied

2024-10-02 23:14 UTC, LeninCat commented
-hybrid trace changes added (effects added)
-linterhell

2025-01-13 08:56 UTC, LeninCat commented
any update on merge?

2025-01-13 13:21 UTC, LiddulBOFH commented
Sorry, it's been a hot minute since I've really sat down to do things. For the most part it looks good, just one of those micro optimizations, that IFTP variable still bugs me particularly when its defined and used a single time like that, given how conditionals work it'd be better in this case to call the function where it's needed instead of setting it in memory and then reading it. I'll merge and make a few other changes before updating workshop.

2025-01-13 13:21 UTC, merged

2025-01-14 04:52 UTC, LeninCat commented
Thanks for the merge, as for the IFTP i had to keep it the way it is to prevent the eye angle recoil from continuously applying more than intended when the player has more ping than like 20. There might be another way to not use this method to prevent the eye angle creep but i don't know how.